# Streamlit Configuration File
# This file controls various Streamlit settings for better development experience

[server]
# Automatically reruns the app when files are saved
runOnSave = true



[theme]
# Optional: Set theme colors (uncomment and customize if desired)
# primaryColor = "#FF6B6B"
# backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
# textColor = "#262730" 